config/routes.rb
Rails.application.routes.draw do
  resources :hostgroups

  resources :hosts

  resources :users

end

app/models/host.rb
class Host < ActiveRecord::Base
end

app/models/hostgroup.rb
class Hostgroup < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hostgroups_controller.rb
class HostgroupsController < ApplicationController
  before_action :set_hostgroup, only: [:show, :edit, :update, :destroy]

  # GET /hostgroups
  # GET /hostgroups.json
  def index
    @hostgroups = Hostgroup.all
  end

  # GET /hostgroups/1
  # GET /hostgroups/1.json
  def show
  end

  # GET /hostgroups/new
  def new
    @hostgroup = Hostgroup.new
  end

  # GET /hostgroups/1/edit
  def edit
  end

  # POST /hostgroups
  # POST /hostgroups.json
  def create
    @hostgroup = Hostgroup.new(hostgroup_params)

    respond_to do |format|
      if @hostgroup.save
        format.html { redirect_to @hostgroup, notice: 'Hostgroup was successfully created.' }
        format.json { render :show, status: :created, location: @hostgroup }
      else
        format.html { render :new }
        format.json { render json: @hostgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hostgroups/1
  # PATCH/PUT /hostgroups/1.json
  def update
    respond_to do |format|
      if @hostgroup.update(hostgroup_params)
        format.html { redirect_to @hostgroup, notice: 'Hostgroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @hostgroup }
      else
        format.html { render :edit }
        format.json { render json: @hostgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hostgroups/1
  # DELETE /hostgroups/1.json
  def destroy
    @hostgroup.destroy
    respond_to do |format|
      format.html { redirect_to hostgroups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hostgroup
      @hostgroup = Hostgroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hostgroup_params
      params.require(:hostgroup).permit(:hostgroup_name, :alias, :members, :hostgroup_members, :note)
    end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: 'Host was successfully created.' }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: 'Host was successfully updated.' }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_params
      params.require(:host).permit(:hostname, :alias, :display_name, :address, :parents, :hostgroups, :check_command, :check_period, :notification_interval, :notification_period)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:prename, :surname, :email, :password, :salt, :created_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hostgroups_helper.rb
module HostgroupsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hostgroups/_form.html.erb
<%= form_for(@hostgroup) do |f| %>
  <% if @hostgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hostgroup.errors.count, "error") %> prohibited this hostgroup from being saved:</h2>

      <ul>
      <% @hostgroup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hostgroup_name %><br>
    <%= f.text_field :hostgroup_name %>
  </div>
  <div class="field">
    <%= f.label :alias %><br>
    <%= f.text_field :alias %>
  </div>
  <div class="field">
    <%= f.label :members %><br>
    <%= f.text_field :members %>
  </div>
  <div class="field">
    <%= f.label :hostgroup_members %><br>
    <%= f.text_field :hostgroup_members %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hostgroups/edit.html.erb
<h1>Editing hostgroup</h1>

<%= render 'form' %>

<%= link_to 'Show', @hostgroup %> |
<%= link_to 'Back', hostgroups_path %>

app/views/hostgroups/index.html.erb
<h1>Listing hostgroups</h1>

<table>
  <thead>
    <tr>
      <th>Hostgroup name</th>
      <th>Alias</th>
      <th>Members</th>
      <th>Hostgroup members</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hostgroups.each do |hostgroup| %>
      <tr>
        <td><%= hostgroup.hostgroup_name %></td>
        <td><%= hostgroup.alias %></td>
        <td><%= hostgroup.members %></td>
        <td><%= hostgroup.hostgroup_members %></td>
        <td><%= hostgroup.note %></td>
        <td><%= link_to 'Show', hostgroup %></td>
        <td><%= link_to 'Edit', edit_hostgroup_path(hostgroup) %></td>
        <td><%= link_to 'Destroy', hostgroup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hostgroup', new_hostgroup_path %>

app/views/hostgroups/new.html.erb
<h1>New hostgroup</h1>

<%= render 'form' %>

<%= link_to 'Back', hostgroups_path %>

app/views/hostgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hostgroup name:</strong>
  <%= @hostgroup.hostgroup_name %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @hostgroup.alias %>
</p>

<p>
  <strong>Members:</strong>
  <%= @hostgroup.members %>
</p>

<p>
  <strong>Hostgroup members:</strong>
  <%= @hostgroup.hostgroup_members %>
</p>

<p>
  <strong>Note:</strong>
  <%= @hostgroup.note %>
</p>

<%= link_to 'Edit', edit_hostgroup_path(@hostgroup) %> |
<%= link_to 'Back', hostgroups_path %>

app/views/hosts/_form.html.erb
<%= form_for(@host) do |f| %>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% @host.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hostname %><br>
    <%= f.text_field :hostname %>
  </div>
  <div class="field">
    <%= f.label :alias %><br>
    <%= f.text_field :alias %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br>
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :parents %><br>
    <%= f.text_field :parents %>
  </div>
  <div class="field">
    <%= f.label :hostgroups %><br>
    <%= f.text_field :hostgroups %>
  </div>
  <div class="field">
    <%= f.label :check_command %><br>
    <%= f.text_field :check_command %>
  </div>
  <div class="field">
    <%= f.label :check_period %><br>
    <%= f.text_field :check_period %>
  </div>
  <div class="field">
    <%= f.label :notification_interval %><br>
    <%= f.number_field :notification_interval %>
  </div>
  <div class="field">
    <%= f.label :notification_period %><br>
    <%= f.text_field :notification_period %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hosts/edit.html.erb
<h1>Editing host</h1>

<%= render 'form' %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

app/views/hosts/index.html.erb
<h1>Listing hosts</h1>

<table>
  <thead>
    <tr>
      <th>Hostname</th>
      <th>Alias</th>
      <th>Display name</th>
      <th>Address</th>
      <th>Parents</th>
      <th>Hostgroups</th>
      <th>Check command</th>
      <th>Check period</th>
      <th>Notification interval</th>
      <th>Notification period</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hosts.each do |host| %>
      <tr>
        <td><%= host.hostname %></td>
        <td><%= host.alias %></td>
        <td><%= host.display_name %></td>
        <td><%= host.address %></td>
        <td><%= host.parents %></td>
        <td><%= host.hostgroups %></td>
        <td><%= host.check_command %></td>
        <td><%= host.check_period %></td>
        <td><%= host.notification_interval %></td>
        <td><%= host.notification_period %></td>
        <td><%= link_to 'Show', host %></td>
        <td><%= link_to 'Edit', edit_host_path(host) %></td>
        <td><%= link_to 'Destroy', host, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Host', new_host_path %>

app/views/hosts/new.html.erb
<h1>New host</h1>

<%= render 'form' %>

<%= link_to 'Back', hosts_path %>

app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hostname:</strong>
  <%= @host.hostname %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @host.alias %>
</p>

<p>
  <strong>Display name:</strong>
  <%= @host.display_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @host.address %>
</p>

<p>
  <strong>Parents:</strong>
  <%= @host.parents %>
</p>

<p>
  <strong>Hostgroups:</strong>
  <%= @host.hostgroups %>
</p>

<p>
  <strong>Check command:</strong>
  <%= @host.check_command %>
</p>

<p>
  <strong>Check period:</strong>
  <%= @host.check_period %>
</p>

<p>
  <strong>Notification interval:</strong>
  <%= @host.notification_interval %>
</p>

<p>
  <strong>Notification period:</strong>
  <%= @host.notification_period %>
</p>

<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'Back', hosts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iciconf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prename %><br>
    <%= f.text_field :prename %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :salt %><br>
    <%= f.text_field :salt %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Prename</th>
      <th>Surname</th>
      <th>Email</th>
      <th>Password</th>
      <th>Salt</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.prename %></td>
        <td><%= user.surname %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.salt %></td>
        <td><%= user.created_at %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prename:</strong>
  <%= @user.prename %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @user.surname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @user.created_at %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>